#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                               0
// GS Chronicles Trainer Defines
#define TRAINER_PASSERBY_BOY_CHIKORITA             1
#define TRAINER_PASSERBY_BOY_CYNDAQUIL             2
#define TRAINER_PASSERBY_BOY_TOTODILE              3
#define TRAINER_RIVAL_KRIS_ROUTE29                 4
#define TRAINER_RIVAL_ETHAN_ROUTE29                5
#define TRAINER_SUPER_NERD_MICK                    6
#define TRAINER_SAGE_CHINNEN                       7
#define TRAINER_SAGE_MOKUNEN                       8
#define TRAINER_SAGE_EISO                          9
#define TRAINER_SAGE_SONEN                        10
#define TRAINER_SAGE_KAKUNEN                      11
#define TRAINER_SAGE_KAINEN                       12
#define TRAINER_ELDER_LI                          13
#define TRAINER_YOUNGSTER_JOEY                    14
#define TRAINER_YOUNGSTER_MIKEY                   15
#define TRAINER_BUG_CATCHER_DON                   16
#define TRAINER_LASS_CHIKA                        17
#define TRAINER_BUG_CATCHER_WADE                  18
#define TRAINER_BIRD_KEEPER_ABE                   19
#define TRAINER_BIRD_KEEPER_RYLEIGH               20
#define TRAINER_PICNICKER_DAHLIA                  21
#define TRAINER_POKEMANIAC_JIM                    22
#define TRAINER_TEAM_ROCKET_GRUNT_1               23
#define TRAINER_RIVAL_ETHAN_ROUTE32               24
#define TRAINER_RIVAL_KRIS_ROUTE32                25
#define TRAINER_YOUNGSTER_JEFFREY                 26
#define TRAINER_PICNICKER_ROXANNE                 27
#define TRAINER_CAMPER_BRAWLY                     28
#define TRAINER_FISHERMAN_COLE                    29
#define TRAINER_FISHERMAN_RON                     30
#define TRAINER_FISHERMAN_JARVIS                  31
#define TRAINER_LASS_RILEY                        32
#define TRAINER_PSYCHIC_F_JENNY                   33
#define TRAINER_BIRD_KEEPER_JACK                  34
#define TRAINER_TEAM_ROCKET_GRUNT_2               35
#define TRAINER_FIREBREATHER_KEANE                36
#define TRAINER_HIKER_RUSSEL                      37
#define TRAINER_HIKER_TRAVIS                      38
#define TRAINER_FIREBREATHER_THEO                 39
#define TRAINER_SUPER_NERD_AKIRA                  40
#define TRAINER_FIREBREATHER_RONNIE               41
#define TRAINER_BLACK_BELT_KOJIRO                 42
#define TRAINER_HIKER_JIMBO                       43
#define TRAINER_TEAM_ROCKET_GRUNT_3               44
#define TRAINER_TEAM_ROCKET_GRUNT_4               45
#define TRAINER_TEAM_ROCKET_GRUNT_5               46
#define TRAINER_ROCKET_EXECUTIVE_PROTON_1         47
#define TRAINER_BUG_CATCHER_COLTON                48
#define TRAINER_TWINS_MARY_AND_SUE                49
#define TRAINER_CAMPER_KENTA                      50
#define TRAINER_PICNICKER_JULIET                  51
#define TRAINER_BUG_CATCHER_MOE                   52
#define TRAINER_LEADER_BUGSY_1                    53
#define TRAINER_TEAM_ROCKET_GRUNT_6               54
#define TRAINER_PKMN_BREEDER_M_DRAKE              55
#define TRAINER_BEAUTY_BRITNEY                    56
#define TRAINER_PICNICKER_JOAN                    57
#define TRAINER_BUG_CATCHER_CONNOR                58
#define TRAINER_RIVAL_KRIS_ROUTE34                59
#define TRAINER_RIVAL_ETHAN_ROUTE34               60
#define TRAINER_YOUNGSTER_OWEN                    61
#define TRAINER_POKE_FAN_M_DEVON                  62
#define TRAINER_PICNICKER_SHARONA                 63
#define TRAINER_HEX_MANIAC_STELLA                 64
#define TRAINER_PKMN_BREEDER_M_JACOB              65
#define TRAINER_YOUNGSTER_CHRIS                   66
#define TRAINER_OFFICER_PETER                     67
#define TRAINER_OFFICER_PARKER                    68
#define TRAINER_LASS_ARLENE                       69
#define TRAINER_BEAUTY_LORETTA                    70
#define TRAINER_PICNICKER_ALLIE                   71
#define TRAINER_POKE_FAN_F_VERA                   72
#define TRAINER_POKE_FAN_M_ERIC                   73
#define TRAINER_LEADER_WHITNEY_1                  74
#define TRAINER_SUPER_NERD_BONJI                  75
#define TRAINER_JUGGLER_GLENN                     76
#define TRAINER_POKEMANIAC_OSCAR                  77
#define TRAINER_SUPER_NERD_MATT                   78
#define TRAINER_BATTLE_GIRL_SHELLY                79
#define TRAINER_CAMPER_TIMMY                      80
#define TRAINER_PICNICKER_COURTNEY                81
#define TRAINER_YOUNGSTER_CARLOS                  82
#define TRAINER_FIREBREATHER_SCOURGE              83
#define TRAINER_JUGGLER_NOLAND                    84
#define TRAINER_BUG_CATCHER_LOUIS                 85
#define TRAINER_BIRD_KEEPER_MIKE                  86
#define TRAINER_LASS_JACKIE                       87
#define TRAINER_POKE_FAN_F_LARISSA                88
#define TRAINER_LASS_GINA                         89
#define TRAINER_POKEMANIAC_CALVIN                 90
#define TRAINER_PICNICKER_LILLIE                  91
#define TRAINER_POKE_FAN_M_LUCAS                  92
#define TRAINER_PSYCHIC_M_VIZZIO                  93
#define TRAINER_SCHOOL_KID_DONNY                  94
#define TRAINER_LASS_BEATRICE                     95
#define TRAINER_TEAM_ROCKET_GRUNT_7               96
#define TRAINER_TEAM_ROCKET_GRUNT_8               97
#define TRAINER_TEAM_ROCKET_GRUNT_9               98
#define TRAINER_TEAM_ROCKET_GRUNT_10              99
#define TRAINER_TEAM_ROCKET_GRUNT_11             100
#define TRAINER_TEAM_ROCKET_GRUNT_12             101
#define TRAINER_TEAM_ROCKET_GRUNT_13             102
#define TRAINER_TEAM_ROCKET_GRUNT_14             103
#define TRAINER_TEAM_ROCKET_GRUNT_15             104
#define TRAINER_ROCKET_EXECUTIVE_PROTON_2        105
#define TRAINER_CHANNELER_USAGI                  106
#define TRAINER_SAGE_AISO                        107
#define TRAINER_CHANNELER_RUMIKO                 108
#define TRAINER_HEX_MANIAC_LINA                  109
#define TRAINER_SAGE_GENDO                       110
#define TRAINER_LEADER_MORTY_1                   111
#define TRAINER_TWINS_MEI_AND_REI                112
#define TRAINER_PSYCHIC_F_JEMINA                 113
#define TRAINER_ROCKET_EXECUTIVE_ARIANA_1        114
#define TRAINER_TEAM_ROCKET_GRUNT_16             115
#define TRAINER_BURGLAR_GORDON                   116
#define TRAINER_SAILOR_SAMSON                    117
#define TRAINER_BEAUTY_ROBIN                     118
#define TRAINER_PICNICKER_CRISSY                 119
#define TRAINER_BIRD_KEEPER_DARIUS               120
#define TRAINER_PSYCHIC_M_WADE                   121
#define TRAINER_BEAUTY_RELI                      122
#define TRAINER_PSYCHIC_M_MORRIS                 123
#define TRAINER_POKE_FAN_F_GIOVANNA              124
#define TRAINER_POKE_FAN_M_GIORNO                125
#define TRAINER_SAILOR_SAIBOT                    126
#define TRAINER_ACE_TRAINER_M_DAVIS              127
#define TRAINER_GENTLEMAN_BYRON                  128
#define TRAINER_SAILOR_HUDSON                    129
#define TRAINER_BIRD_KEEPER_STEVE                130
#define TRAINER_GENTLEMAN_ANDRE                  131
#define TRAINER_LASS_KAYLA                       132
#define TRAINER_SAILOR_LINO                      133
#define TRAINER_POKEMANIAC_EDMOND                134
#define TRAINER_SAILOR_TREVOR                    135
#define TRAINER_TUBER_F_LENORA                   136
#define TRAINER_SAILOR_DUNCAN                    137
#define TRAINER_FISHERMAN_HUEY                   138
#define TRAINER_SWIMMER_M_DYLAN                  139
#define TRAINER_SWIMMER_F_BRIANNA                140
#define TRAINER_TUBER_M_DWAYNE                   141
#define TRAINER_SWIMMER_M_LIAM                   142
#define TRAINER_SWIMMER_F_JANICE                 143
#define TRAINER_TUBER_F_ERNESTINE                144
#define TRAINER_HIKER_RICKY                      145
#define TRAINER_HIKER_JEFF                       146
#define TRAINER_SUPER_NERD_ROY                   147
#define TRAINER_SUPER_NERD_TOMMY                 148
#define TRAINER_PSYCHIC_F_BEA                    149
#define TRAINER_POKE_FAN_F_DIANA                 150
#define TRAINER_LEADER_CHUCK_1                   151
#define TRAINER_LEADER_JASMINE_1                 152
#define TRAINER_LEADER_LORELEI_1                 153
#define TRAINER_LEADER_CLAIR_1                   154
#define TRAINER_SWIMMER_F_CAITLIN                155
#define TRAINER_SWIMMER_M_HAROLD                 156
#define TRAINER_SWIMMER_M_DUNCAN                 157
#define TRAINER_SWIMMER_F_SOFIA                  158
#define TRAINER_SWIMMER_F_MARTHA                 159
#define TRAINER_SWIMMER_M_BRYCE                  160
#define TRAINER_SWIMMER_F_HANNAH                 161
#define TRAINER_SWIMMER_M_MARK                   162
#define TRAINER_SWIMMER_F_EMMA                   163
#define TRAINER_FISHERMAN_COOPER                 164
#define TRAINER_SUPER_NERD_STEVE                 165
#define TRAINER_HIKER_WINSTON                    166
#define TRAINER_POKEMANIAC_DAWSON                167
#define TRAINER_REPORTER_CIEL_1                  168
#define TRAINER_RIVAL_KRIS_UNUSED                169
#define TRAINER_RIVAL_ETHAN_UNUSED               170
#define TRAINER_MYSTICAL_MAN_EUSINE              171
#define TRAINER_BLACK_BELT_GLENN                 172
#define TRAINER_BATTLE_GIRL_LASHAWNA             173
#define TRAINER_BLACK_BELT_BRANDO                174
#define TRAINER_BATTLE_GIRL_SHARON               175
#define TRAINER_BLACK_BELT_DIMAGGIO              176
#define TRAINER_BLACK_BELT_ERIK                  177
#define TRAINER_JUGGLER_AVERY                    178
#define TRAINER_SUPER_NERD_DEREK                 179
#define TRAINER_GENTLEMAN_ZACHARY                180
#define TRAINER_LASS_SONYA                       181
#define TRAINER_OFFICER_FRANKLIN                 182
#define TRAINER_RIVAL_KRIS_ECRUTEAKSHRINE        183
#define TRAINER_RIVAL_ETHAN_ECRUTEAKSHRINE       184
#define TRAINER_BLACK_BELT_KIYO                  185
#define TRAINER_CAMPER_SPENCER                   186
#define TRAINER_PICNICKER_TIFFANY                187
#define TRAINER_POKEMANIAC_BRENT                 188
#define TRAINER_POKEMANIAC_BECKET                189
#define TRAINER_POKEMANIAC_RON                   190
#define TRAINER_FISHERMAN_WADE                   191
#define TRAINER_TEAM_ROCKET_GRUNT_17             192
#define TRAINER_TEAM_ROCKET_GRUNT_18             193
#define TRAINER_TEAM_ROCKET_GRUNT_19             194
#define TRAINER_TEAM_ROCKET_GRUNT_20             195
#define TRAINER_TEAM_ROCKET_GRUNT_21             196
#define TRAINER_TEAM_ROCKET_GRUNT_22             197
#define TRAINER_TEAM_ROCKET_SCIENTIST_1          198
#define TRAINER_TEAM_ROCKET_GRUNT_23             199
#define TRAINER_TEAM_ROCKET_GRUNT_24             200
#define TRAINER_ROCKET_ADMIN_BERKEL_1            201
#define TRAINER_ROCKET_EXECUTIVE_PETREL_1        202
#define TRAINER_ROCKET_EXECUTIVE_ARIANA_2        203
#define TRAINER_BOARDER_NICHOLAS                 204
#define TRAINER_BOARDER_JAXON                    205
#define TRAINER_BOARDER_WILLIAM                  206
#define TRAINER_SKIER_LINA                       207
#define TRAINER_SKIER_BJORN                      208
#define TRAINER_SKIER_ELAINE                     209
#define TRAINER_FISHERMAN_BOJACK                 210
#define TRAINER_FISHERMAN_DINO                   211
#define TRAINER_FISHERMAN_DWAYNE                 212
#define TRAINER_SUPER_NERD_MACKEY                213
#define TRAINER_ACE_TRAINER_F_TETRA              214
#define TRAINER_ACE_TRAINER_M_NED                215
#define TRAINER_ACE_TRAINER_M_JADEN              216
#define TRAINER_ACE_TRAINER_F_IRIS               217
#define TRAINER_ACE_TRAINER_M_GENE               218
#define TRAINER_FISHERMAN_LEWIS                  219
#define TRAINER_POKEMANIAC_BAILY                 220
#define TRAINER_FISHERMAN_BRAXTON                221
#define TRAINER_BIRD_KEEPER_BERNIE               222
#define TRAINER_RIVAL_KRIS_BLACKTHORNCITY        223
#define TRAINER_RIVAL_ETHAN_BLACKTHORNCITY       224
#define TRAINER_TEAM_ROCKET_GRUNT_25             225
#define TRAINER_TEAM_ROCKET_GRUNT_26             226
#define TRAINER_TEAM_ROCKET_GRUNT_27             227
#define TRAINER_TEAM_ROCKET_GRUNT_28             228
#define TRAINER_TEAM_ROCKET_GRUNT_29             229
#define TRAINER_TEAM_ROCKET_GRUNT_30             230
#define TRAINER_TEAM_ROCKET_SCIENTIST_2          231
#define TRAINER_TEAM_ROCKET_GRUNT_31             232
#define TRAINER_TEAM_ROCKET_GRUNT_32             233
#define TRAINER_TEAM_ROCKET_GRUNT_33             234
#define TRAINER_TEAM_ROCKET_GRUNT_34             235
#define TRAINER_TEAM_ROCKET_SCIENTIST_3          236
#define TRAINER_ROCKET_ADMIN_BERKEL_2            237
#define TRAINER_TEAM_ROCKET_GRUNT_35             238
#define TRAINER_BURGLAR_DAVID                    239
#define TRAINER_BURGLAR_TONY                     240
#define TRAINER_TEAM_ROCKET_GRUNT_36             241
#define TRAINER_TEAM_ROCKET_GRUNT_37             242
#define TRAINER_TEAM_ROCKET_GRUNT_38             243
#define TRAINER_TEAM_ROCKET_GRUNT_39             244
#define TRAINER_ROCKET_EXECUTIVE_PETREL_2        245
#define TRAINER_ROCKET_EXECUTIVE_PROTON_3        246
#define TRAINER_ROCKET_EXECUTIVE_ARIANA_3        247
#define TRAINER_ROCKET_EXECUTIVE_ARCHER_1        248
#define TRAINER_TEAM_ROCKET_GRUNT_40             249
#define TRAINER_TEAM_ROCKET_GRUNT_41             250
#define TRAINER_ELDER_MOKAI                      251
#define TRAINER_ACE_TRAINER_M_RAUL               252
#define TRAINER_ACE_TRAINER_M_ISAIAH             253
#define TRAINER_ACE_TRAINER_F_LENA               254
#define TRAINER_ACE_TRAINER_F_JOANNE             255
#define TRAINER_ACE_TRAINER_M_COREY              256
#define TRAINER_ACE_TRAINER_M_CHASE              257
#define TRAINER_ACE_TRAINER_F_BERTHA             258
#define TRAINER_TWINS_LUA_AND_LUCA               259
#define TRAINER_KIMONO_GIRL_ZUKI                 260
#define TRAINER_KIMONO_GIRL_NAOKO                261
#define TRAINER_KIMONO_GIRL_MIKI                 262
#define TRAINER_KIMONO_GIRL_SAYO                 263
#define TRAINER_KIMONO_GIRL_KUNI                 264
#define TRAINER_ACE_TRAINER_M_WILLIAM            265
#define TRAINER_ACE_TRAINER_F_TANYA              266
#define TRAINER_ACE_TRAINER_M_RONNIE             267
#define TRAINER_SWIMMER_M_JOE                    268
#define TRAINER_SWIMMER_F_SHEILA                 269
#define TRAINER_GENTLEMAN_TERRANCE               270
#define TRAINER_ACE_TRAINER_F_NORA               271
#define TRAINER_ACE_TRAINER_M_GIBSON             272
#define TRAINER_SWIMMER_F_GRACE                  273
#define TRAINER_YOUNG_COUPLE_JOEY_AND_MAI        274
#define TRAINER_ACE_TRAINER_M_ROBBIE             275
#define TRAINER_ACE_TRAINER_M_ARNOLD             276
#define TRAINER_BIRD_KEEPER_DANTE                277
#define TRAINER_ACE_TRAINER_F_CONNIE             278
#define TRAINER_HIKER_DARIUS                     279
#define TRAINER_ACE_TRAINER_F_ZOSSIE             280
#define TRAINER_HIKER_TYRON                      281
#define TRAINER_ACE_TRAINER_M_CAMERON            282
#define TRAINER_SUPER_NERD_PRESTON               283
#define TRAINER_ACE_TRAINER_M_RANDALL            284
#define TRAINER_ACE_TRAINER_M_LUCA               285
#define TRAINER_ROCKER_JIMI                      286
#define TRAINER_ACE_TRAINER_F_ANYA               287
#define TRAINER_ACE_COUPLE_BENNY_AND_KAI         288
#define TRAINER_JUGGLER_SHAWN                    289
#define TRAINER_ACE_TRAINER_M_GREGORY            290
#define TRAINER_ACE_TRAINER_F_KATRINA            291
#define TRAINER_ACE_TRAINER_M_KAYDEN             292
#define TRAINER_ACE_TRAINER_M_NATE               293
#define TRAINER_ACE_TRAINER_F_PRISCILLA          294
#define TRAINER_ACE_TRAINER_F_MINA               295
#define TRAINER_ACE_TRAINER_M_JASON              296
#define TRAINER_FISHERMAN_COREY                  297
#define TRAINER_ACE_TRAINER_F_TRINA              298
#define TRAINER_BOARDER_JOHN                     299
#define TRAINER_LEADER_PRYCE_1                   300
#define TRAINER_PKMN_TRAINER_KRIS                301
#define TRAINER_PKMN_TRAINER_ETHAN               302
#define TRAINER_SKIER_LENORA                     303
#define TRAINER_BOARDER_BENNY                    304
#define TRAINER_SKIER_BRENDA                     305
#define TRAINER_BOARDER_CHESTER                  306
#define TRAINER_HIKER_WILTON                     307
#define TRAINER_SUPER_NERD_FLYNN                 308
#define TRAINER_HIKER_JACOB                      309
#define TRAINER_ACE_TRAINER_M_ROGER              310
#define TRAINER_HIKER_REED                       311
#define TRAINER_ACE_TRAINER_F_MELINA             312
#define TRAINER_POKE_FAN_M_CARTER                313
#define TRAINER_BEAUTY_TAYLOR                    314
#define TRAINER_HIKER_BECK                       315
#define TRAINER_HIKER_MARLON                     316
#define TRAINER_HIKER_BENSON                     317
#define TRAINER_CAMPER_MIKE                      318
#define TRAINER_CAMPER_STANLEY                   319
#define TRAINER_PICNICKER_WENDY                  320
#define TRAINER_LEADER_FALKNER_1                 321
#define TRAINER_BLACK_BELT_ATSUSHI               322
#define TRAINER_TEAM_ROCKET_GRUNT_42             323
#define TRAINER_TEAM_ROCKET_GRUNT_43             324
#define TRAINER_TEAM_ROCKET_GRUNT_44             325
#define TRAINER_SILVER_ILEXFOREST_QUILAVA        326
#define TRAINER_SILVER_ILEXFOREST_CROCONAW       327
#define TRAINER_SILVER_ILEXFOREST_BAYLEEF        328
#define TRAINER_SILVER_BURNEDTOWER_QUILAVA       329
#define TRAINER_SILVER_BURNEDTOWER_CROCONAW      330
#define TRAINER_SILVER_BURNEDTOWER_BAYLEEF       331
#define TRAINER_SILVER_GOLDENROD_TYPHLOSION      332
#define TRAINER_SILVER_GOLDENROD_FERALIGATR      333
#define TRAINER_SILVER_GOLDENROD_MEGANIUM        334
#define TRAINER_PKMN_TRAINER_LANCE_PARTNER       335
#define TRAINER_SILVER_GOLDENROD_PARTNER         336
#define TRAINER_LEADER_FALKNER_2                 337
#define TRAINER_LEADER_BUGSY_2                   338
#define TRAINER_LEADER_WHITNEY_2                 339
#define TRAINER_LEADER_MORTY_2                   340
#define TRAINER_LEADER_CHUCK_2                   341
#define TRAINER_LEADER_JASMINE_2                 342
#define TRAINER_LEADER_PRYCE_2                   343
#define TRAINER_LEADER_CLAIR_2                   344
#define TRAINER_HEX_MANIAC_BLAIR                 345
#define TRAINER_ACE_TRAINER_F_ALEXIA             346
#define TRAINER_ACE_TRAINER_F_RILEY              347
#define TRAINER_ACE_TRAINER_M_ANDRIY             348
#define TRAINER_HIKER_DEREK                      349
#define TRAINER_ELITE_FOUR_AILE_2                350
#define TRAINER_ELITE_FOUR_WILL_2                351
#define TRAINER_ELITE_FOUR_KOGA_2                352
#define TRAINER_ELITE_FOUR_KAREN_2               353
#define TRAINER_TEAM_ROCKET_GRUNT_45             358
#define TRAINER_HEX_MANIAC_GERMANA               359
#define TRAINER_TEAM_ROCKET_SCIENTIST_4          360
#define TRAINER_CHALLENGER_SILVER_TYPHLOSION     361
#define TRAINER_CHALLENGER_SILVER_FERALIGATR     362
#define TRAINER_CHALLENGER_SILVER_MEGANIUM       363
#define TRAINER_CHALLENGER_JOEY                  364
#define TRAINER_CHALLENGER_SAYO                  365
#define TRAINER_CHALLENGER_LORELEI               366
#define TRAINER_CHALLENGER_CLAIR                 367
#define TRAINER_CHALLENGER_PROF_ELM_TYPHLOSION   368
#define TRAINER_CHALLENGER_PROF_ELM_FERALIGATR   369
#define TRAINER_CHALLENGER_PROF_ELM_MEGANIUM     370

//GS Chronicles Kanto Trainers

/*Vermilion City Gym*/
#define TRAINER_JUGGLER_GATTO                    354
#define TRAINER_GUITARIST_CARLOS                 355
#define TRAINER_GENTLEMAN_RYAN                   356

/*S.S. Aqua Fist*/
#define TRAINER_POKE_FAN_M_HOWARD                357
#define TRAINER_TWINS_MAY_AND_MEI                371
#define TRAINER_FIREBREATHER_BARNES              372
#define TRAINER_HIKER_QUINTON                    373
#define TRAINER_SAILOR_HANDSOME                  374
#define TRAINER_PICNICKER_JEANNIE                375
#define TRAINER_JUGGLER_GARRET                   376
#define TRAINER_SAILOR_PETE                      377
#define TRAINER_BURGLAR_COOPER                   378

#define TRAINER_AGATHA_TAG_TEAM                  379
/*
#define TRAINER_TEAM_ROCKET_GRUNT_30             380
#define TRAINER_TEAM_ROCKET_GRUNT_31             381
#define TRAINER_TEAM_ROCKET_GRUNT_32             382
#define TRAINER_TEAM_ROCKET_GRUNT_33             383
#define TRAINER_TEAM_ROCKET_GRUNT_34             384
#define TRAINER_TEAM_ROCKET_GRUNT_35             385
#define TRAINER_TEAM_ROCKET_GRUNT_36             386
#define TRAINER_TEAM_ROCKET_GRUNT_37             387
#define TRAINER_TEAM_ROCKET_GRUNT_38             388
#define TRAINER_TEAM_ROCKET_GRUNT_39             389
#define TRAINER_TEAM_ROCKET_GRUNT_40             390
#define TRAINER_TEAM_ROCKET_GRUNT_41             391*/
#define TRAINER_COOLTRAINER_SAMUEL               392
#define TRAINER_COOLTRAINER_GEORGE               393
#define TRAINER_COOLTRAINER_COLBY                394
#define TRAINER_COOLTRAINER_PAUL                 395
#define TRAINER_COOLTRAINER_ROLANDO              396
#define TRAINER_COOLTRAINER_GILBERT              397
#define TRAINER_COOLTRAINER_OWEN                 398
#define TRAINER_COOLTRAINER_BERKE                399
#define TRAINER_COOLTRAINER_YUJI                 400
#define TRAINER_COOLTRAINER_WARREN               401
#define TRAINER_COOLTRAINER_MARY                 402
#define TRAINER_COOLTRAINER_CAROLINE             403
#define TRAINER_COOLTRAINER_ALEXA                404
#define TRAINER_COOLTRAINER_SHANNON              405
#define TRAINER_COOLTRAINER_NAOMI                406
#define TRAINER_COOLTRAINER_BROOKE               407
#define TRAINER_COOLTRAINER_AUSTINA              408
#define TRAINER_COOLTRAINER_JULIE                409
#define TRAINER_ELITE_FOUR_AILE                  410//JOHTO ELITE 4
#define TRAINER_ELITE_FOUR_WILL                  411//JOHTO ELITE 4
#define TRAINER_ELITE_FOUR_KOGA                  412//JOHTO ELITE 4
#define TRAINER_ELITE_FOUR_KAREN                 413//JOHTO ELITE 4
#define TRAINER_LEADER_BROCK                     414
#define TRAINER_LEADER_MISTY                     415
#define TRAINER_LEADER_LT_SURGE_1                416
#define TRAINER_LEADER_ERIKA                     417
#define TRAINER_LEADER_KOGA                      418
#define TRAINER_LEADER_BLAINE                    419
#define TRAINER_LEADER_SABRINA                   420
#define TRAINER_GENTLEMAN_THOMAS                 421
#define TRAINER_GENTLEMAN_ARTHUR                 422
#define TRAINER_LEADER_LT_SURGE_2                423
#define TRAINER_GENTLEMAN_NORTON                 424
#define TRAINER_GENTLEMAN_WALTER                 425
#define TRAINER_SILVER_LEAGUE_TYPHLOSION         426//RIVAL JOHTO LEAGUE
#define TRAINER_SILVER_LEAGUE_FERALIGATR         427//RIVAL JOHTO LEAGUE
#define TRAINER_SILVER_LEAGUE_MEGANIUM           428//RIVAL JOHTO LEAGUE
#define TRAINER_RIVAL_POKENON_TOWER_SQUIRTLE     429
#define TRAINER_RIVAL_POKENON_TOWER_BULBASAUR    430
#define TRAINER_RIVAL_POKENON_TOWER_CHARMANDER   431
#define TRAINER_RIVAL_SILPH_SQUIRTLE             432
#define TRAINER_RIVAL_SILPH_BULBASAUR            433
#define TRAINER_RIVAL_SILPH_CHARMANDER           434
#define TRAINER_RIVAL_ROUTE22_LATE_SQUIRTLE      435
#define TRAINER_RIVAL_ROUTE22_LATE_BULBASAUR     436
#define TRAINER_RIVAL_ROUTE22_LATE_CHARMANDER    437
#define TRAINER_CHAMPION_FIRST_SQUIRTLE          438
#define TRAINER_CHAMPION_FIRST_BULBASAUR         439
#define TRAINER_CHAMPION_FIRST_CHARMANDER        440
#define TRAINER_CHANNELER_PATRICIA               441
#define TRAINER_CHANNELER_CARLY                  442
#define TRAINER_CHANNELER_HOPE                   443
#define TRAINER_CHANNELER_PAULA                  444
#define TRAINER_CHANNELER_LAUREL                 445
#define TRAINER_CHANNELER_JODY                   446
#define TRAINER_CHANNELER_TAMMY                  447
#define TRAINER_CHANNELER_RUTH                   448
#define TRAINER_CHANNELER_KARINA                 449
#define TRAINER_CHANNELER_JANAE                  450
#define TRAINER_CHANNELER_ANGELICA               451
#define TRAINER_CHANNELER_EMILIA                 452
#define TRAINER_CHANNELER_JENNIFER               453
#define TRAINER_CHANNELER_1                      454
#define TRAINER_CHANNELER_2                      455
#define TRAINER_CHANNELER_3                      456
#define TRAINER_CHANNELER_4                      457
#define TRAINER_CHANNELER_5                      458
#define TRAINER_CHANNELER_6                      459
#define TRAINER_CHANNELER_7                      460
#define TRAINER_CHANNELER_8                      461
#define TRAINER_CHANNELER_AMANDA                 462
#define TRAINER_CHANNELER_STACY                  463
#define TRAINER_CHANNELER_TASHA                  464
#define TRAINER_HIKER_JEREMY                     465
#define TRAINER_PICNICKER_ALMA                   466
#define TRAINER_PICNICKER_SUSIE                  467
#define TRAINER_PICNICKER_VALERIE                468
#define TRAINER_PICNICKER_GWEN                   469
#define TRAINER_BIKER_VIRGIL                     470
#define TRAINER_CAMPER_FLINT                     471
#define TRAINER_PICNICKER_MISSY                  472
#define TRAINER_PICNICKER_IRENE                  473
#define TRAINER_PICNICKER_DANA                   474
#define TRAINER_PICNICKER_ARIANA                 475
#define TRAINER_PICNICKER_LEAH                   476
#define TRAINER_CAMPER_JUSTIN                    477
#define TRAINER_PICNICKER_YAZMIN                 478
#define TRAINER_PICNICKER_KINDRA                 479
#define TRAINER_PICNICKER_BECKY                  480
#define TRAINER_PICNICKER_CELIA                  481
#define TRAINER_GENTLEMAN_BROOKS                 482
#define TRAINER_GENTLEMAN_LAMAR                  483
#define TRAINER_TWINS_ELI_ANNE                   484
#define TRAINER_COOL_COUPLE_RAY_TYRA             485
#define TRAINER_YOUNG_COUPLE_GIA_JES             486
#define TRAINER_TWINS_KIRI_JAN                   487
#define TRAINER_CRUSH_KIN_RON_MYA                488
#define TRAINER_YOUNG_COUPLE_LEA_JED             489
#define TRAINER_SIS_AND_BRO_LIA_LUC              490
#define TRAINER_SIS_AND_BRO_LIL_IAN              491
#define TRAINER_BUG_CATCHER_3                    492
#define TRAINER_BUG_CATCHER_4                    493
#define TRAINER_BUG_CATCHER_5                    494
#define TRAINER_BUG_CATCHER_6                    495
#define TRAINER_BUG_CATCHER_7                    496
#define TRAINER_BUG_CATCHER_8                    497
#define TRAINER_YOUNGSTER_BEN_3                  498
#define TRAINER_YOUNGSTER_BEN_4                  499
#define TRAINER_YOUNGSTER_CHAD_2                 500
#define TRAINER_LASS_RELI_2                      501
#define TRAINER_LASS_RELI_3                      502
#define TRAINER_YOUNGSTER_TIMMY_2                503
#define TRAINER_YOUNGSTER_TIMMY_3                504
#define TRAINER_YOUNGSTER_TIMMY_4                505
#define TRAINER_YOUNGSTER_CHAD_3                 506
#define TRAINER_LASS_JANICE_2                    507
#define TRAINER_LASS_JANICE_3                    508
#define TRAINER_YOUNGSTER_CHAD_4                 509
#define TRAINER_HIKER_FRANKLIN_2                 510
#define TRAINER_PKMN_PROF_PROF_OAK               511
#define TRAINER_PLAYER_BRENDAN                   512
#define TRAINER_PLAYER_MAY                       513
#define TRAINER_PLAYER_RED                       514
#define TRAINER_PLAYER_LEAF                      515
#define TRAINER_TEAM_ROCKET_GRUNT_92             516
#define TRAINER_PSYCHIC_JACLYN                   517
#define TRAINER_CRUSH_GIRL_SHARON                518
#define TRAINER_TUBER_AMIRA                      519
#define TRAINER_PKMN_BREEDER_ALIZE               520
#define TRAINER_PKMN_RANGER_NICOLAS              521
#define TRAINER_PKMN_RANGER_MADELINE             522
#define TRAINER_AROMA_LADY_NIKKI                 523
#define TRAINER_RUIN_MANIAC_STANLY               524
#define TRAINER_LADY_JACKI                       525
#define TRAINER_PAINTER_DAISY                    526
#define TRAINER_BIKER_GOON                       527
#define TRAINER_BIKER_GOON_2                     528
#define TRAINER_BIKER_GOON_3                     529
#define TRAINER_BIKER_2                          530
#define TRAINER_BUG_CATCHER_ANTHONY              531
#define TRAINER_BUG_CATCHER_CHARLIE              532
#define TRAINER_TWINS_ELI_ANNE_2                 533
#define TRAINER_YOUNGSTER_JOHNSON                534
#define TRAINER_BIKER_RICARDO                    535
#define TRAINER_BIKER_JAREN                      536
/*#define TRAINER_TEAM_ROCKET_GRUNT_43           537
#define TRAINER_TEAM_ROCKET_GRUNT_44             538
#define TRAINER_TEAM_ROCKET_GRUNT_45             539
#define TRAINER_TEAM_ROCKET_GRUNT_46             540
#define TRAINER_TEAM_ROCKET_GRUNT_47             541
#define TRAINER_TEAM_ROCKET_GRUNT_48             542*/
#define TRAINER_TEAM_ROCKET_ADMIN                543
#define TRAINER_TEAM_ROCKET_ADMIN_2              544
#define TRAINER_SCIENTIST_GIDEON                 545
#define TRAINER_SWIMMER_FEMALE_AMARA             546
#define TRAINER_SWIMMER_FEMALE_MARIA             547
#define TRAINER_SWIMMER_FEMALE_ABIGAIL           548
#define TRAINER_SWIMMER_MALE_FINN                549
#define TRAINER_SWIMMER_MALE_GARRETT             550
#define TRAINER_FISHERMAN_TOMMY                  551
#define TRAINER_CRUSH_GIRL_TANYA                 552
#define TRAINER_BLACK_BELT_SHEA                  553
#define TRAINER_BLACK_BELT_HUGH                  554
#define TRAINER_CAMPER_BRYCE                     555
#define TRAINER_PICNICKER_CLAIRE                 556
#define TRAINER_CRUSH_KIN_MIK_KIA                557
#define TRAINER_AROMA_LADY_VIOLET                558
#define TRAINER_TUBER_ALEXIS                     559
#define TRAINER_TWINS_JOY_MEG                    560
#define TRAINER_SWIMMER_FEMALE_TISHA             561
#define TRAINER_PAINTER_CELINA                   562
#define TRAINER_PAINTER_RAYNA                    563
#define TRAINER_LADY_GILLIAN                     564
#define TRAINER_YOUNGSTER_DESTIN                 565
#define TRAINER_SWIMMER_MALE_TOBY                566
/*#define TRAINER_TEAM_ROCKET_GRUNT_49           567
#define TRAINER_TEAM_ROCKET_GRUNT_50             568
#define TRAINER_TEAM_ROCKET_GRUNT_51             569*/
#define TRAINER_BIRD_KEEPER_MILO                 570
#define TRAINER_BIRD_KEEPER_CHAZ                 571
#define TRAINER_BIRD_KEEPER_HAROLD               572
#define TRAINER_FISHERMAN_TYLOR                  573
#define TRAINER_SWIMMER_MALE_MYMO                574
#define TRAINER_SWIMMER_FEMALE_NICOLE            575
#define TRAINER_SIS_AND_BRO_AVA_GEB              576
#define TRAINER_AROMA_LADY_ROSE                  577
#define TRAINER_SWIMMER_MALE_SAMIR               578
#define TRAINER_SWIMMER_FEMALE_DENISE            579
#define TRAINER_TWINS_MIU_MIA                    580
#define TRAINER_HIKER_EARL                       581
#define TRAINER_RUIN_MANIAC_FOSTER               582
#define TRAINER_RUIN_MANIAC_LARRY                583
#define TRAINER_HIKER_DARYL                      584
#define TRAINER_POKEMANIAC_HECTOR                585
#define TRAINER_PSYCHIC_DARIO                    586
#define TRAINER_PSYCHIC_RODETTE                  587
#define TRAINER_AROMA_LADY_MIAH                  588
#define TRAINER_YOUNG_COUPLE_EVE_JON             589
#define TRAINER_JUGGLER_MASON                    590
#define TRAINER_CRUSH_GIRL_CYNDY                 591
#define TRAINER_CRUSH_GIRL_JOCELYN               592
#define TRAINER_TAMER_EVAN                       593
#define TRAINER_POKEMANIAC_MARK_2                594
#define TRAINER_PKMN_RANGER_LOGAN                595
#define TRAINER_PKMN_RANGER_JACKSON              596
#define TRAINER_PKMN_RANGER_BETH                 597
#define TRAINER_PKMN_RANGER_KATELYN              598
#define TRAINER_COOLTRAINER_LEROY                599
#define TRAINER_COOLTRAINER_MICHELLE             600
#define TRAINER_COOL_COUPLE_LEX_NYA              601
#define TRAINER_RUIN_MANIAC_BRANDON              602
#define TRAINER_RUIN_MANIAC_BENJAMIN             603
#define TRAINER_PAINTER_EDNA                     604
#define TRAINER_GENTLEMAN_CLIFFORD               605
#define TRAINER_LADY_SELPHY                      606
#define TRAINER_RUIN_MANIAC_LAWSON               607
#define TRAINER_PSYCHIC_LAURA                    608
#define TRAINER_PKMN_BREEDER_BETHANY             609
#define TRAINER_PKMN_BREEDER_ALLISON             610
#define TRAINER_BUG_CATCHER_GARRET               611
#define TRAINER_BUG_CATCHER_JONAH                612
#define TRAINER_BUG_CATCHER_VANCE                613
#define TRAINER_YOUNGSTER_NASH                   614
#define TRAINER_YOUNGSTER_CORDELL                615
#define TRAINER_LASS_DALIA                       616
#define TRAINER_LASS_JOANA                       617
#define TRAINER_CAMPER_RILEY                     618
#define TRAINER_PICNICKER_MARCY                  619
#define TRAINER_RUIN_MANIAC_LAYTON               620
#define TRAINER_PICNICKER_KELSEY_2               621
#define TRAINER_PICNICKER_KELSEY_3               622
#define TRAINER_PICNICKER_KELSEY_4               623
#define TRAINER_CAMPER_RICKY_2                   624
#define TRAINER_CAMPER_RICKY_3                   625
#define TRAINER_CAMPER_RICKY_4                   626
#define TRAINER_CAMPER_JEFF_2                    627
#define TRAINER_CAMPER_JEFF_3                    628
#define TRAINER_CAMPER_JEFF_4                    629
#define TRAINER_PICNICKER_ISABELLE_2             630
#define TRAINER_PICNICKER_ISABELLE_3             631
#define TRAINER_PICNICKER_ISABELLE_4             632
#define TRAINER_YOUNGSTER_YASU_2                 633
#define TRAINER_YOUNGSTER_YASU_3                 634
#define TRAINER_ENGINEER_BERNIE_2                635
#define TRAINER_GAMER_DARIAN_2                   636
#define TRAINER_CAMPER_CHRIS_2                   637
#define TRAINER_CAMPER_CHRIS_3                   638
#define TRAINER_CAMPER_CHRIS_4                   639
#define TRAINER_PICNICKER_ALICIA_2               640
#define TRAINER_PICNICKER_ALICIA_3               641
#define TRAINER_PICNICKER_ALICIA_4               642
#define TRAINER_HIKER_JEREMY_2                   643
#define TRAINER_POKEMANIAC_MARK_3                644
#define TRAINER_POKEMANIAC_HERMAN_2              645
#define TRAINER_POKEMANIAC_HERMAN_3              646
#define TRAINER_HIKER_TRENT_2                    647
#define TRAINER_LASS_MEGAN_2                     648
#define TRAINER_LASS_MEGAN_3                     649
#define TRAINER_SUPER_NERD_GLENN_2               650
#define TRAINER_GAMER_RICH_2                     651
#define TRAINER_BIKER_JAREN_2                    652
#define TRAINER_FISHERMAN_ELLIOT_2               653
#define TRAINER_ROCKER_LUCA_2                    654
#define TRAINER_BEAUTY_SHEILA_2                  655
#define TRAINER_BIRD_KEEPER_ROBERT_2             656
#define TRAINER_BIRD_KEEPER_ROBERT_3             657
#define TRAINER_PICNICKER_SUSIE_2                658
#define TRAINER_PICNICKER_SUSIE_3                659
#define TRAINER_PICNICKER_SUSIE_4                660
#define TRAINER_BIKER_LUKAS_2                    661
#define TRAINER_BIRD_KEEPER_BENNY_2              662
#define TRAINER_BIRD_KEEPER_BENNY_3              663
#define TRAINER_BIRD_KEEPER_MARLON_2             664
#define TRAINER_BIRD_KEEPER_MARLON_3             665
#define TRAINER_BEAUTY_GRACE_2                   666
#define TRAINER_BIRD_KEEPER_CHESTER_2            667
#define TRAINER_BIRD_KEEPER_CHESTER_3            668
#define TRAINER_PICNICKER_BECKY_2                669
#define TRAINER_PICNICKER_BECKY_3                670
#define TRAINER_PICNICKER_BECKY_4                671
#define TRAINER_CRUSH_KIN_RON_MYA_2              672
#define TRAINER_CRUSH_KIN_RON_MYA_3              673
#define TRAINER_CRUSH_KIN_RON_MYA_4              674
#define TRAINER_BIKER_RUBEN_2                    675
#define TRAINER_CUE_BALL_CAMRON_2                676
#define TRAINER_BIKER_JAXON_2                    677
#define TRAINER_CUE_BALL_ISAIAH_2                678
#define TRAINER_CUE_BALL_COREY_2                 679
#define TRAINER_BIRD_KEEPER_JACOB_2              680
#define TRAINER_BIRD_KEEPER_JACOB_3              681
#define TRAINER_SWIMMER_FEMALE_ALICE_2           682
#define TRAINER_SWIMMER_MALE_DARRIN_2            683
#define TRAINER_PICNICKER_MISSY_2                684
#define TRAINER_PICNICKER_MISSY_3                685
#define TRAINER_FISHERMAN_WADE_2                 686
#define TRAINER_SWIMMER_MALE_JACK_2              687
#define TRAINER_SIS_AND_BRO_LIL_IAN_2            688
#define TRAINER_SIS_AND_BRO_LIL_IAN_3            689
#define TRAINER_SWIMMER_MALE_FINN_2              690
#define TRAINER_CRUSH_GIRL_SHARON_2              691
#define TRAINER_CRUSH_GIRL_SHARON_3              692
#define TRAINER_CRUSH_GIRL_TANYA_2               693
#define TRAINER_CRUSH_GIRL_TANYA_3               694
#define TRAINER_BLACK_BELT_SHEA_2                695
#define TRAINER_BLACK_BELT_SHEA_3                696
#define TRAINER_BLACK_BELT_HUGH_2                697
#define TRAINER_BLACK_BELT_HUGH_3                698
#define TRAINER_CRUSH_KIN_MIK_KIA_2              699
#define TRAINER_CRUSH_KIN_MIK_KIA_3              700
#define TRAINER_TUBER_AMIRA_2                    701
#define TRAINER_TWINS_JOY_MEG_2                  702
#define TRAINER_PAINTER_RAYNA_2                  703
#define TRAINER_YOUNGSTER_DESTIN_2               704
#define TRAINER_PKMN_BREEDER_ALIZE_2             705
#define TRAINER_YOUNG_COUPLE_GIA_JES_2           706
#define TRAINER_YOUNG_COUPLE_GIA_JES_3           707
#define TRAINER_BIRD_KEEPER_MILO_2               708
#define TRAINER_BIRD_KEEPER_CHAZ_2               709
#define TRAINER_BIRD_KEEPER_HAROLD_2             710
#define TRAINER_SWIMMER_FEMALE_NICOLE_2          711
#define TRAINER_PSYCHIC_JACLYN_2                 712
#define TRAINER_SWIMMER_MALE_SAMIR_2             713
#define TRAINER_HIKER_EARL_2                     714
#define TRAINER_RUIN_MANIAC_LARRY_2              715
#define TRAINER_POKEMANIAC_HECTOR_2              716
#define TRAINER_PSYCHIC_DARIO_2                  717
#define TRAINER_PSYCHIC_RODETTE_2                718
#define TRAINER_JUGGLER_MASON_2                  719
#define TRAINER_PKMN_RANGER_NICOLAS_2            720
#define TRAINER_PKMN_RANGER_MADELINE_2           721
#define TRAINER_CRUSH_GIRL_CYNDY_2               722
#define TRAINER_TAMER_EVAN_2                     723
#define TRAINER_PKMN_RANGER_JACKSON_2            724
#define TRAINER_PKMN_RANGER_KATELYN_2            725
#define TRAINER_COOLTRAINER_LEROY_2              726
#define TRAINER_COOLTRAINER_MICHELLE_2           727
#define TRAINER_COOL_COUPLE_LEX_NYA_2            728
#define TRAINER_BUG_CATCHER_COLTON_2             729
#define TRAINER_BUG_CATCHER_COLTON_3             730
#define TRAINER_BUG_CATCHER_COLTON_4             731
#define TRAINER_SWIMMER_MALE_MATTHEW_2           732
#define TRAINER_SWIMMER_MALE_TONY_2              733
#define TRAINER_SWIMMER_FEMALE_MELISSA_2         734
#define TRAINER_ELITE_FOUR_LORELEI_2             735
#define TRAINER_ELITE_FOUR_BRUNO_2               736
#define TRAINER_ELITE_FOUR_AGATHA_2              737
#define TRAINER_ELITE_FOUR_LANCE_2               738
#define TRAINER_CHAMPION_REMATCH_SQUIRTLE        739
#define TRAINER_CHAMPION_REMATCH_BULBASAUR       740
#define TRAINER_CHAMPION_REMATCH_CHARMANDER      741
#define TRAINER_CUE_BALL_PAXTON                  742

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is 
//       only space for 25 additional trainers before trainer flag space overflows.
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define NUM_TRAINERS                             743
#define MAX_TRAINERS_COUNT                       768

#endif  // GUARD_CONSTANTS_OPPONENTS_H